export const DIAGNOSTICS_FPS_SAMPLE_MS = 1000
export const DIAGNOSTICS_MEMORY_SAMPLE_MS = 2000
export const DIAGNOSTICS_LONG_TASK_THRESHOLD_MS = 50
export const DIAGNOSTICS_WARN_FPS = 45
export const DIAGNOSTICS_WARN_LONG_TASKS_PER_MIN = 20
export const DIAGNOSTICS_WARN_MEMORY_MB = 350
